{% set version = "0.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rtables.officer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rtables.officer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rtables.officer/rtables.officer_{{ version }}.tar.gz
  sha256: 3ee48ca00a15718665c26903012ac98f58bd3bd479a1321640ff7d3e63f563fd

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate >=2.1.0
    - r-flextable >=0.9.10
    - r-formatters >=0.5.12
    - r-lifecycle >=0.2.0
    - r-officer >=0.7.1
    - r-rlistings >=0.2.13
    - r-rtables >=0.6.15
    - r-stringi >=1.6
    - r-systemfonts
  run:
    - r-base
    - r-checkmate >=2.1.0
    - r-flextable >=0.9.10
    - r-formatters >=0.5.12
    - r-lifecycle >=0.2.0
    - r-officer >=0.7.1
    - r-rlistings >=0.2.13
    - r-rtables >=0.6.15
    - r-stringi >=1.6
    - r-systemfonts

test:
  commands:
    - $R -e "library('rtables.officer')"           # [not win]
    - "\"%R%\" -e \"library('rtables.officer')\""  # [win]

about:
  home: https://github.com/insightsengineering/rtables.officer, https://insightsengineering.github.io/rtables.officer/
  license: Apache-2.0
  summary: Designed to create and display complex tables with R, the 'rtables' R package allows cells in an 'rtables' object to contain any high-dimensional data structure, which can then be displayed with cell-specific formatting instructions. Additionally, the 'rtables.officer' package supports export formats related to
    the Microsoft Office software suite, including Microsoft Word ('docx') and Microsoft PowerPoint ('pptx').
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
